class MyAnimeList

  def add(namespace, id, data = {})
    add_title(namespace, "add", id, format_values(data))
  end

  def update(namespace, id, data = {})
    add_title(namespace, "update", id, format_values(data))
  end

  # Allows the authenticating user to delete anime/manga title.
  # http://myanimelist.net/api/animelist|mangalist/id.xml
  # where id is id of title.
  # === Returns
  # Integer:: Unique ID of the row generated by the insert
  def delete(namespace, id)
    if result = do_request("#{namespace}/delete/#{id}.xml", "POST")
      return result
    end
  end

  private

  # Allows the authenticating user to add or update anime/manga title.
  # http://myanimelist.net/api/animelist|mangalist/id.xml
  # where id is id of title.
  # === Returns
  # Integer:: Unique ID of the row generated by the insert
  def add_title(namespace, action, id, data)
    if id = do_request("#{namespace}/#{action}/#{id}.xml", "POST", data)
      # It returns HTML now, dunno why.
      return "Added"
    end
  end

end
